### PR TITLE
Add total contributed to user profiles

### PR DESCRIPTION
**Pull request by JasoonS**

### CODE REVIEW

**Comment by JasoonS** [comment]
image
 Total contributed is new.
 
 Did some other small refactors (added some common 'BN' values that we use to the "CONSTANTS" files)

**Comment by JasoonS** [comment]
Check it out here: https://ui-ishc0k7rw.vercel.app/#user/0xa337be3d8d2e5b70f29b730c44c14017626c75a1

**Comment by moose-code** [comment]
Awesome! Some feedback:

The monthly contribution part is static, so maybe no need to show the extra decimal places that don't count up?

Total contribution part looks great. 

For another time, but it would be great to have the patrons avaiable deposit and when its going to expire on their profile too. This shows on all the animals they own and should also show on their profile :D 

@JasoonS

**Review by moose-code — APPROVED** [review]
Awesome. Just those comments about possible improvements to this page.

**Comment by JasoonS** [comment]
> The monthly contribution part is static, so maybe no need to show the extra decimal places that don't count up?

Yeah, I was just being lazy and using the same component. But I agree.

> it would be great to have the patrons avaiable deposit and when its going to expire on their profile too.

I was thinking we just show this when users are logged in maybe. This info might not be as relevant to other users browsing the website?

**Comment by JasoonS** [comment]
image

Fixed

**Pull request merged**
